module DragonHangView

  def self.stage1
    puts " ____________________"
    puts "| .__________________|"
    puts "| | / /      "
    puts "| |/ /       "
    puts "| | /        "
    puts "| |/         "
    puts "| |          "
    puts "| |          "
    puts "| |         "
    puts "| |        "
    puts "| |       "
    puts "| |     "
    puts "| |   "
    puts "| | "
    puts "| |      "
    puts "| |       "
    puts "| |       "
    puts "| |       "
    puts "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|"
    puts "|\"|\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\"|"
    puts "| |                   | |"
    puts ": :                   : :"
    puts ". .                   . ."
  end

  def self.stage2
    puts " ___________.._______"
    puts "| .__________))______|"
    puts "| | / /      ||"
    puts "| |/ /       ||"
    puts "| | /        ||"
    puts "| |/         ||"
    puts "| |          ||"
    puts "| |          ()"
    puts "| |         "
    puts "| |        "
    puts "| |       "
    puts "| |     "
    puts "| |   "
    puts "| | "
    puts "| |      "
    puts "| |       "
    puts "| |       "
    puts "| |       "
    puts "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|"
    puts "|\"|\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\"|"
    puts "| |                   | |"
    puts ": :                   : :"
    puts ". .                   . ."
  end

  def self.stage4
    puts " ___________.._______"
    puts "| .__________))______|"
    puts "| | / /      ||"
    puts "| |/ /       ||"
    puts "| | /        ||.-''."
    puts "| |/         |/  _  \\"
    puts "| |          ||  `/,|"
    puts "| |          (\\`_.'"
    puts "| |         "
    puts "| |        "
    puts "| |       "
    puts "| |     "
    puts "| |   "
    puts "| | "
    puts "| |      "
    puts "| |       "
    puts "| |       "
    puts "| |       "
    puts "\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|"
    puts "|\"|\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"|\"|"
    puts "| |                   | |"
    puts ": :                   : :"
    puts ". .                   . ."
  end

  def self.stage5
    puts " ___________.._______"
    puts "| .__________))______|"
    puts "| | / /      ||"
    puts "| |/ /       ||"
    puts "| | /        ||.-''."
    puts "| |/         |/  _  \\"
    puts "| |          ||  `/,|"
    puts "| |          (\\`_.'"
    puts "| |         .-`--'."
    puts "| |         Y . . Y"
    puts "| |          |   | "
    puts "| |          | . | "
    puts "| |          |   | "
    puts "| |           ---"
    puts "| |          "
    puts "| |          "
    puts "| |          "
    puts "| |         "
    puts "\"\"\"\"\"\"\"\"\"\"|_`-' `-' |\"\"\"|"
    puts "|\"|\"\"\"\"\"\"\"\\         '\"|\"|"
    puts "| |        \\ \\        | |"
    puts ": :         \\ \\       : :"
    puts ". .          `'       . ."
  end

  def self.dead
    puts " ___________.._______"
    puts "| .__________))______|"
    puts "| | / /      ||"
    puts "| |/ /       ||"
    puts "| | /        ||.-''."
    puts "| |/         |/  _  \\"
    puts "| |          ||  `/,|"
    puts "| |          (\\`_.'"
    puts "| |         .-`--'."
    puts "| |        /Y . . Y\\"
    puts "| |       // |   | \\\\"
    puts "| |      //  | . |  \\\\"
    puts "| |     ')   |   |   (`"
    puts "| |          ||-||"
    puts "| |          || ||"
    puts "| |          || ||"
    puts "| |          || ||"
    puts "| |         / | | \\"
    puts "\"\"\"\"\"\"\"\"\"\"|_`-' `-' |\"\"\"|"
    puts "|\"|\"\"\"\"\"\"\"\\         '\"|\"|"
    puts "| |        \\ \\        | |"
    puts ": :         \\ \\       : :"
    puts ". .          `'       . ."
  end

end

DragonHangView.stage5
